# Generated by Django 6.0.1 on 2026-03-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_service_options_alter_service_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Services'},
        ),
    ]
